from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
import os
import sys

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def generate_card(prescription_data, qr_path, lang='english'):
    """Generate printable prescription card PDF"""
    
    output_dir = os.path.join(os.path.dirname(__file__), 'output')
    os.makedirs(output_dir, exist_ok=True)
    
    output_path = os.path.join(output_dir, 'prescription_card.pdf')
    
    try:
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        
        # Simple translations
        translations = {
            'marathi': {
                'Patient': 'रुग्ण',
                'Doctor': 'डॉक्टर',
                'Medicines': 'औषधे',
                'Dosage': 'डोस',
                'Frequency': 'वारंवारता',
                'Instruction': 'सूचना',
                'Emergency': 'आपत्कालीन'
            },
            'hindi': {
                'Patient': 'मरीज',
                'Doctor': 'डॉक्टर',
                'Medicines': 'दवाइयां',
                'Dosage': 'खुराक',
                'Frequency': 'आवृत्ति',
                'Instruction': 'निर्देश',
                'Emergency': 'आपातकालीन'
            },
            'english': {
                'Patient': 'Patient',
                'Doctor': 'Doctor',
                'Medicines': 'Medicines',
                'Dosage': 'Dosage',
                'Frequency': 'Frequency',
                'Instruction': 'Instruction',
                'Emergency': 'Emergency'
            }
        }
        
        t = translations.get(lang, translations['english'])
        
        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "MEDICAL PRESCRIPTION")
        c.setFont("Helvetica", 9)
        c.drawString(50, height - 70, "MediMate - Smart Medication Companion")
        
        # Patient Info
        y = height - 110
        c.setFont("Helvetica-Bold", 11)
        c.drawString(50, y, f"{t['Patient']}: {prescription_data.get('patient_name', 'N/A')}")
        y -= 20
        c.drawString(50, y, f"{t['Doctor']}: {prescription_data.get('doctor', 'N/A')}")
        y -= 20
        c.drawString(50, y, f"Date: {prescription_data.get('date', 'N/A')}")
        
        # Emergency Contact
        if prescription_data.get('emergency_contact'):
            y -= 20
            c.drawString(50, y, f"{t['Emergency']}: {prescription_data.get('emergency_contact')}")
        
        # Medicines Section
        y -= 30
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, f"{t['Medicines']}:")
        
        y -= 25
        medicines = prescription_data.get('medicines', [])
        c.setFont("Helvetica", 10)
        
        for med in medicines:
            if y < 100:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica-Bold", 12)
                c.drawString(50, y, f"{t['Medicines']} (cont):")
                y -= 25
                c.setFont("Helvetica", 10)
            
            if isinstance(med, dict):
                name = med.get('name', 'Unknown')
                dosage = med.get('dosage', '')
                frequency = med.get('frequency', '')
                instruction = med.get('instruction', '')
            else:
                name = med
                dosage = ''
                frequency = ''
                instruction = ''
            
            c.setFont("Helvetica-Bold", 10)
            c.drawString(60, y, f"• {name} {dosage}")
            y -= 15
            
            c.setFont("Helvetica", 9)
            if frequency:
                c.drawString(70, y, f"  ⏰ {t['Frequency']}: {frequency}")
                y -= 15
            if instruction:
                c.drawString(70, y, f"  📌 {t['Instruction']}: {instruction}")
                y -= 15
            
            y -= 10
        
        # QR Code
        if os.path.exists(qr_path):
            try:
                from reportlab.lib.utils import ImageReader
                qr_img = ImageReader(qr_path)
                c.drawImage(qr_img, width - 100, height - 100, width=80, height=80)
                c.setFont("Helvetica", 7)
                c.drawString(width - 95, height - 115, "Scan for details")
            except Exception as e:
                print(f"QR placement error: {e}")
        
        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(50, 40, "This is a computer-generated prescription")
        c.drawString(50, 25, f"Generated by MediMate | Language: {lang.upper()}")
        
        c.save()
        return output_path
        
    except Exception as e:
        print(f"Card generation error: {e}")
        # Create a simple fallback PDF
        c = canvas.Canvas(output_path, pagesize=A4)
        c.drawString(100, 500, "Prescription Card")
        c.drawString(100, 480, f"Patient: {prescription_data.get('patient_name', 'N/A')}")
        c.drawString(100, 460, f"Doctor: {prescription_data.get('doctor', 'N/A')}")
        c.save()
        return output_path